/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v2gCommunication.client;
import java.awt.Toolkit;
import v2gCommunication.client.ui.*;

/**
 *
 * @author alexander
 */
public class ClientMainAPI extends javax.swing.JFrame {
    private String userName;
    
    /**
     * Creates new form ClientMainAPI
     */
    public ClientMainAPI() {
        initComponents();
        setIcon();
        dataAccess = new v2gCommunication.client.ui.DataAccess();
        panelUserManagement = new v2gCommunication.client.ui.PanelUserManagement();
        panelVehicleManagement = new v2gCommunication.client.ui.PanelVehicleManagement();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStatus = new javax.swing.JLabel();
        jLabelLoginInfo = new javax.swing.JLabel();
        jTabbedPaneMainContent = new javax.swing.JTabbedPane();
        jMenuBarMainMenu = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemLogon = new javax.swing.JMenuItem();
        jMenuItemLogoff = new javax.swing.JMenuItem();
        jSeparatorFileMenu = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("V2X Client");

        jLabelStatus.setText("Status:");

        jLabelLoginInfo.setText("Not Connected");

        jMenuFile.setMnemonic('F');
        jMenuFile.setText("File");

        jMenuItemLogon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemLogon.setMnemonic('i');
        jMenuItemLogon.setText("Login");
        jMenuItemLogon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogonActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemLogon);

        jMenuItemLogoff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemLogoff.setMnemonic('o');
        jMenuItemLogoff.setText("Logout");
        jMenuItemLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoffActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemLogoff);
        jMenuFile.add(jSeparatorFileMenu);

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemExit.setMnemonic('x');
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBarMainMenu.add(jMenuFile);

        setJMenuBar(jMenuBarMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(jLabelStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLoginInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jTabbedPaneMainContent, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPaneMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus)
                    .addComponent(jLabelLoginInfo)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

                                       
    private void jMenuItemLogonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogonActionPerformed
        // TODO add your handling code here:
        LoginDialog loginDialog = new LoginDialog(this, true);
        loginDialog.setVisible(true);
        if(loginDialog.loginDataEntered()){
            // add method check login credentials
            userName = loginDialog.getName();
            ClientMethods.logon(loginDialog.getName(), loginDialog.getPassword());
            ClientMethods.getUserRights(loginDialog.getName());
            this.jLabelLoginInfo.setText("Connected");
            jTabbedPaneMainContent.addTab("User Management", panelUserManagement);
            jTabbedPaneMainContent.addTab("Vehicle Management", panelVehicleManagement);
            jTabbedPaneMainContent.addTab("Data Access", dataAccess);
        }
        loginDialog.dispose();
    }//GEN-LAST:event_jMenuItemLogonActionPerformed

    private void jMenuItemLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoffActionPerformed
        // TODO add your handling code here:
        ClientMethods.logoff(userName);
        this.jLabelLoginInfo.setText("Not Connected");
        jTabbedPaneMainContent.remove(panelUserManagement);
        jTabbedPaneMainContent.remove(panelVehicleManagement);
        jTabbedPaneMainContent.remove(dataAccess);
        
    }//GEN-LAST:event_jMenuItemLogoffActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // Add code to proerly log out:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel( javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientMainAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientMainAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientMainAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientMainAPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientMainAPI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLoginInfo;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JMenuBar jMenuBarMainMenu;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLogoff;
    private javax.swing.JMenuItem jMenuItemLogon;
    private javax.swing.JPopupMenu.Separator jSeparatorFileMenu;
    private javax.swing.JTabbedPane jTabbedPaneMainContent;
    // End of variables declaration//GEN-END:variables

    
    // private Variables for dynamically added componentes
    private v2gCommunication.client.ui.DataAccess dataAccess;
    private v2gCommunication.client.ui.PanelUserManagement panelUserManagement;
    private v2gCommunication.client.ui.PanelVehicleManagement panelVehicleManagement;
    // End of vairbles declaration 
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/v2gCommunication/client/icons/mainlogo_small.png")));
    }
}
