/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v2gCommunication.client.ui;

/**
 *
 * @author alexander
 */
public class PanelUserManagement extends javax.swing.JPanel {

    /**
     * Creates new form NewUserManagement
     */
    public PanelUserManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUserHeading = new javax.swing.JLabel();
        jLabelUserIcon = new javax.swing.JLabel();
        jButtonAddAccount = new javax.swing.JButton();
        jButtonDeleteAccount = new javax.swing.JButton();
        jButtonAlppy = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanelUserList = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListUsers = new javax.swing.JList();
        jTabbedPaneAccountData = new javax.swing.JTabbedPane();
        panelUserData1 = new v2gCommunication.client.ui.PanelUserData();
        panelVehicleAccess1 = new v2gCommunication.client.ui.PanelVehicleAccess();

        jLabelUserHeading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelUserHeading.setText("Users and Privileges");

        jLabelUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/v2gCommunication/client/icons/user3.png"))); // NOI18N

        jButtonAddAccount.setText("Add Account");

        jButtonDeleteAccount.setText("Delete");

        jButtonAlppy.setText("Apply");

        jLabel1.setText("User Accounts");

        jListUsers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListUsers);

        javax.swing.GroupLayout jPanelUserListLayout = new javax.swing.GroupLayout(jPanelUserList);
        jPanelUserList.setLayout(jPanelUserListLayout);
        jPanelUserListLayout.setHorizontalGroup(
            jPanelUserListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanelUserListLayout.setVerticalGroup(
            jPanelUserListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserListLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanelUserList);

        jTabbedPaneAccountData.addTab("Account Settings", panelUserData1);
        jTabbedPaneAccountData.addTab("Vehicle Access", panelVehicleAccess1);

        jSplitPane1.setRightComponent(jTabbedPaneAccountData);
        jTabbedPaneAccountData.getAccessibleContext().setAccessibleName("User ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonAddAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDeleteAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAlppy, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelUserIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUserHeading)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelUserHeading)
                    .addComponent(jLabelUserIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddAccount)
                    .addComponent(jButtonDeleteAccount)
                    .addComponent(jButtonAlppy)))
        );

        getAccessibleContext().setAccessibleName("User Management");
        getAccessibleContext().setAccessibleDescription("User Management");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddAccount;
    private javax.swing.JButton jButtonAlppy;
    private javax.swing.JButton jButtonDeleteAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelUserHeading;
    private javax.swing.JLabel jLabelUserIcon;
    private javax.swing.JList jListUsers;
    private javax.swing.JPanel jPanelUserList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPaneAccountData;
    private v2gCommunication.client.ui.PanelUserData panelUserData1;
    private v2gCommunication.client.ui.PanelVehicleAccess panelVehicleAccess1;
    // End of variables declaration//GEN-END:variables
}
