/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v2gCommunication.client.ui;

/**
 *
 * @author alexander
 */
public class PanelVehicleManagement extends javax.swing.JPanel {

    /**
     * Creates new form PanelVehicleManagement
     */
    public PanelVehicleManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogoVehicleManagement = new javax.swing.JLabel();
        jLabelVehicleManagement = new javax.swing.JLabel();
        jButtonAddVehicle = new javax.swing.JButton();
        jButtonDeleteVehicle = new javax.swing.JButton();
        jButtonApplyChanges = new javax.swing.JButton();
        jSplitPaneVehicleManagement = new javax.swing.JSplitPane();
        jPanelListVehicles = new javax.swing.JPanel();
        jLabelListVehciles = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListVehicles = new javax.swing.JList();
        jTabbedPaneVehicleData = new javax.swing.JTabbedPane();
        vehicleData1 = new v2gCommunication.client.ui.VehicleData();

        jLabelLogoVehicleManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/v2gCommunication/client/icons/Cars3.png"))); // NOI18N

        jLabelVehicleManagement.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelVehicleManagement.setText("Vehicles and Properties");

        jButtonAddVehicle.setText("Add Vehicle");

        jButtonDeleteVehicle.setText("Delete");

        jButtonApplyChanges.setText("Apply");

        jLabelListVehciles.setText("Vehicles");

        jListVehicles.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListVehicles);

        javax.swing.GroupLayout jPanelListVehiclesLayout = new javax.swing.GroupLayout(jPanelListVehicles);
        jPanelListVehicles.setLayout(jPanelListVehiclesLayout);
        jPanelListVehiclesLayout.setHorizontalGroup(
            jPanelListVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelListVehciles, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanelListVehiclesLayout.setVerticalGroup(
            jPanelListVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListVehiclesLayout.createSequentialGroup()
                .addComponent(jLabelListVehciles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
        );

        jSplitPaneVehicleManagement.setLeftComponent(jPanelListVehicles);

        jTabbedPaneVehicleData.addTab("VehcileData", vehicleData1);

        jSplitPaneVehicleManagement.setRightComponent(jTabbedPaneVehicleData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAddVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDeleteVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonApplyChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelLogoVehicleManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVehicleManagement)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSplitPaneVehicleManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLogoVehicleManagement)
                    .addComponent(jLabelVehicleManagement))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPaneVehicleManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddVehicle)
                    .addComponent(jButtonDeleteVehicle)
                    .addComponent(jButtonApplyChanges)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddVehicle;
    private javax.swing.JButton jButtonApplyChanges;
    private javax.swing.JButton jButtonDeleteVehicle;
    private javax.swing.JLabel jLabelListVehciles;
    private javax.swing.JLabel jLabelLogoVehicleManagement;
    private javax.swing.JLabel jLabelVehicleManagement;
    private javax.swing.JList jListVehicles;
    private javax.swing.JPanel jPanelListVehicles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPaneVehicleManagement;
    private javax.swing.JTabbedPane jTabbedPaneVehicleData;
    private v2gCommunication.client.ui.VehicleData vehicleData1;
    // End of variables declaration//GEN-END:variables
}
